version: "3.8"

services:
  frontend:
    image: sreerajrone/tradeport-frontend:latest
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:3000/api
      - HOST=0.0.0.0
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  backend:
    image: sreerajrone/tradeport-backend:latest
    ports:
      - "3000:3000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/api"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  default:
    driver: bridge
