version: "3.8"

services:
  frontend:
    image: sreerajrone/tradeport-frontend:latest
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:3000/api
      - HOST=0.0.0.0
    depends_on:
      - backend

  backend:
    image: sreerajrone/tradeport-backend:latest
    ports:
      - "3000:3000"
