---
- name: Provision TradePort Droplet
  hosts: tradeport
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install system prerequisites
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - git
        state: present

    - name: Add Docker GPG key and repo
      shell: |
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        echo \
          "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        update_cache: yes

    - name: Enable Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Install Docker Compose plugin
      shell: |
        mkdir -p ~/.docker/cli-plugins
        curl -SL https://github.com/docker/compose/releases/download/v2.24.2/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
        chmod +x ~/.docker/cli-plugins/docker-compose

    - name: Upload Docker Compose file
      copy:
        src: ../docker-compose.dev.yml
        dest: /root/docker-compose.dev.yml
        mode: "0644"

    - name: Start services with Docker Compose
      shell: docker compose -f docker-compose.dev.yml up -d
      args:
        chdir: /root
