name: CI – Build, Lint, Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - feature/*
      - bugfix/*

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install and Test Frontend
        working-directory: frontend
        run: |
          npm install
          npm run lint
          npm run test

      - name: Install and Test Backend
        working-directory: backend
        run: |
          npm install
          npm run lint
          npm run test
