name: "eslint-tool-scan"

on:
  push:
    branches: [main, develop, githubcicd]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Cache node_modules
        uses: actions/cache@v3
        id: cache-nodemodules
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        working-directory: frontend
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run ESLint and Generate Report
        working-directory: frontend
        run: |
          mkdir -p reports
          npx eslint src --ext .ts,.tsx -f stylish > reports/eslint-report.txt || true

      - name: Archive ESLint Report
        uses: actions/upload-artifact@v4
        with:
          name: eslint-report
          path: |
            frontend/reports/eslint-report.txt
